name: 'Linkcheck'
description: >
  Check links with linkcheck,
  a tool focused on blazing fast localhost crawling.
branding:
  icon: 'link'
  color: 'green'
inputs:
  arguments:
    description: 'The arguments you would pass to the linkcheck tool'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}
