name: 'Check links with linkcheck'
description: >
  Blazing fast localhost crawling via the linkcheck tool.
branding:
  icon: 'link'
  color: 'green'
inputs:
  arguments:
    description: 'The arguments you would pass to the linkcheck tool'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'sh -c /root/.pub-cache/bin/linkcheck ${{ inputs.arguments }}'
