include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - collection_methods_unrelated_type
    - combinators_ordering
    - comment_references
    - deprecated_member_use_from_same_package
    - discarded_futures
    - implicit_reopen
    - invalid_case_patterns
    - library_annotations
    - matching_super_parameters
    - no_literal_bool_comparisons
    - omit_local_variable_types
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_single_quotes
    - test_types_in_equals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_breaks
    - unnecessary_late
    - unnecessary_library_directive
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - use_enums
    - use_super_parameters
